namespace Opera2Oris.Middlewear;

internal static class LicenseKeys
{
    // Replace this with the content of public.key generated by Opera2Oris.LicenseGenerator.
    // Run: Opera2Oris.LicenseGenerator generate-keys
    // Then paste the content of public.key here.
    public const string PublicKey = "REPLACE_WITH_PUBLIC_KEY_XML";
}
